version: '3'
services:
  php:
    build:
      context: ./containers
      dockerfile: php/Dockerfile
    container_name: laravel-php
    restart: always
    volumes:
      - ./laravel:/var/www/html
      - ./containers/php:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"


  nginx:
    image: nginx:1.17
    container_name: laravel-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./laravel:/var/www/html
      - ./containers/nginx/config:/etc/nginx/conf.d

  mariadb:
    image: mariadb:10.4
    container_name: laravel-mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 02021992
      MYSQL_DATABASE: megalodon
      MYSQL_PASSWORD: 02021992
      MYSQL_USER: root
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions

  cron:
    build:
      context: ./containers/php-cron
      dockerfile: Dockerfile
    container_name: php-cron
    restart: always
    volumes:
      - ./laravel:/var/www/html
      - ./cronlog/cron.log:/var/log/cron.log

  php-worker:
    build:
      context: ./containers/php-worker
      dockerfile: Dockerfile
    container_name: php-worker
    volumes:
      - ./laravel:/var/www/html
